/*
 * tlevision.c
 *
 * Author: Thomas McIlwraith
 * Date: 63/07/2026
 * 
 * Program for generating ephemerides from TLEs.
 * 
 */

#include "file-io/data_structures/application_output/application_output.h"
#include "file-io/internal-products/parameter-evolution-file/parameter_evolution_file.h"
#include "file-io/internal-products/read-json/read_json.h"
#include "file-io/data_structures/tle/tle.h"
#include "tlevision/tlevision_generate_arc.h"
// #include "tlevision_interfaces.h"
#include "utilities/misc/paths/paths.h"
#include "file-io/data_structures/workflow_graph/workflow_graph.h"

int main(int argc, char *argv[]) {

    // Program variables
    execution_settings_t execution_settings = {0};
    StatusCode status = OK;
    workflow_graph_t graph;
    workflow_node_t *this_node = NULL;
    workflow_node_t *input_aTLE_node = NULL;
    workflow_node_t *input_TSPN_node = NULL;
    application_output_t input_aTLE_output = {0};
    application_output_t input_TSPN_output = {0};
    application_output_t output_file = {0};
    tle_t *aTLE = NULL;
    int n_TLE = 0;
    parameter_evolution_file_t TSPN_file = {0};
    parameter_evolution_t TSPN = {0};
    parameter_evolution_file_t *EPHM_files = NULL;
    int n_EPHM = 0;

    // Parse command line, initialise log file
    status = parse_cmdline(&execution_settings, argc, argv);
    if (status != OK) {
        LOG(ERROR, "Failed to parse command line");
        return ERROR;
    }
    init_log(execution_settings.run_title, execution_settings.working_directory, execution_settings.program_name);

    // Load the workflow graph
    status = workflow_graph_read(&graph, &this_node, execution_settings);
    if (status != OK) {
        LOG(ERROR, "Failed to load workflow graph");
        return ERROR;
    }

    // Load the input TLEs node
    status = workflow_graph_find_input_node(&input_aTLE_node, &graph, this_node, "aTLE", "aTLE");
    if (status != OK) {
        LOG(ERROR, "Failed to find aTLE input node");
        return ERROR;
    }

    // Load the outputs from the TLEs node
    status = application_output_read(&input_aTLE_output, execution_settings.working_directory, input_aTLE_node->id);
    if (status != OK) {
        LOG(ERROR, "Failed to read aTLE outputs");
        return ERROR;
    }

    if (input_aTLE_output.n_TLE == 0) {
        LOG(ERROR, "No TLEs were output by %s. Exiting.", input_aTLE_node->program);
        return ERROR;
    }

    // Load the TLE objects into memory
    status = application_output_read_aTLE(&aTLE, &n_TLE, &input_aTLE_output, execution_settings.working_directory);
    if (status != OK) {
        LOG(ERROR, "Failed to load aTLE outputs into memory");
        return ERROR;
    }

    // Load the TSPN node
    status = workflow_graph_find_input_node(&input_TSPN_node, &graph, this_node, "TSPN", "TSPN");
    if (status != OK) {
        LOG(ERROR, "Failed to find TSPN input node");
        return ERROR;
    }

    // Load the outputs from the TSPN node
    status = application_output_read(&input_TSPN_output, execution_settings.working_directory, input_TSPN_node->id);
    if (status != OK) {
        LOG(ERROR, "Failed to read TSPN node outputs");
        return ERROR;
    }

    if (input_TSPN_output.n_TSPN == 0) {
        LOG(ERROR, "Expected TSPN was not generated by %s. Exiting", input_TSPN_node->program);
        return ERROR;
    } else if (input_TSPN_output.n_TSPN != 1) {
        LOG(ERROR, "%d TSPNs were generated by %s when 1 was expected. Exiting", input_TSPN_output.n_TSPN, input_TSPN_node->program);
        return ERROR;
    }

    // Load the TSPN into memory
    status = parameter_evolution_file_read(&TSPN_file, input_TSPN_output.aTSPN[0], execution_settings.working_directory);
    if (status != OK) {
        LOG(ERROR, "Failed to load TSPN parameter evolution file into memory");
        return ERROR;
    }

    // Isolate the timespan from the TSPN evolution file
    status = parameter_evolution_file_get_jd(&TSPN, &TSPN_file);
    if (status != OK) {
        LOG(ERROR, "Failed to find TSPN array in TSPN parameter evolution file");
        return ERROR;
    }

    // Run the propagation for each TLE
    status = ephm_generate_SGP4(&EPHM_files, &n_EPHM, &TSPN, aTLE, n_TLE, 0, execution_settings.run_title); 
    if (status != OK) {
        LOG(ERROR, "Failed to generate ephemerides");
        return ERROR;
    }

    // Write all the output files
    for (int i = 0; i < n_EPHM; i++) {
        status = parameter_evolution_file_write(EPHM_files[i], execution_settings.working_directory);
        if (status != OK) {
            LOG(ERROR, "Failed to write ephemeris file: %s", EPHM_files[i].filename);
            return ERROR;
        } else {
            LOG(INFO, "EPHM data written: %s", EPHM_files[i].filename);

            // add the filename to the list of files to be written to the output file
            status = application_output_add_EPHM(&output_file, EPHM_files[i].filename);
            if (status != OK) {
                LOG(ERROR, "Failed to add EPHM filename to output file");
                return ERROR;
            }

        }
    }

    LOG(INFO, "Successfully generated %d EPHM files", output_file.n_EPHM);

    // Write the program output_file
    status = application_output_write(&output_file, execution_settings.working_directory, execution_settings.run_title);
    if (status != OK) {
        LOG(ERROR, "Failed to write output file");
        return ERROR;
    }

    LOG(INFO, "Program complete: %s (%s)", execution_settings.program_name, execution_settings.run_title);
    return OK;
}

